guid: 22740e5f-f63b-4b82-8629-fb9d4fd74c36
name: V1SkuApplicationGateway
title: Take advantage of features for autoscaling and performance benefits
description: The v2 SKU offers autoscaling to ensure that your Application Gateway
  can scale up as traffic increases. When compared to v1 SKU, v2 has capabilities
  that enhance the performance of the workload. For example, better TLS offload performance,
  quicker deployment and update times, zone redundancy, and more. For more information
  about autoscaling features, see Scaling Application Gateway v2 and WAF v2.If you
  are running v1 SKU Application gateway, consider migrating to the Application gateway
  v2 SKU. For more information, see Migrate Azure Application Gateway and Web Application
  Firewall from v1 to v2.
source:
  type: revcl
  file: ./checklists-ext/wafsg_checklist.en.json
services:
- Azure Application Gateway
resourceTypes:
- microsoft.network/applicationGateways
waf: Performance
labels: {}
links: []
queries: []
