name: wafsg-WebApplicationFirewallRateLimitingRules
title: Take advantage of the rate-limiting rules that are included with a web application
  firewall (WAF).
description: Limit requests to prevent clients from sending too much traffic to your
  application. Rate limiting can help you avoid problems like a retry storm.
source:
  type: wafsg
  file: ./checklists-ext/wafsg_checklist.en.json
resourceTypes:
- microsoft.network/frontdoors
waf: Reliability
labels:
  guid: 4a17bea1-3951-4f73-8de7-cd3193bca5d2
links: []
queries: {}
