guid: b4e3f2d5-a5c6-4d7e-8b2f-c5d9e7a8f0ea
name: ApplicationInsightsStandardTest
title: Use Application Insights Standard test to monitor availability and responsiveness
  of web app or website
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
services:
- App Services
resourceTypes:
- microsoft.web/sites
waf: Reliability
severity: 2
labels: {}
links:
- https://learn.microsoft.com/en-us/azure/azure-monitor/app/availability-standard-tests
queries: []
