guid: c7d3e5f9-a19c-4833-8ca6-1dcb0128e129
name: ApplicationInsightsAvailabilityTests
title: Monitor availability and responsiveness of web app or website using Application
  Insights availability tests
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
services:
- App Services
resourceTypes:
- microsoft.web/sites
waf: Reliability
severity: 1
labels: {}
links:
- https://learn.microsoft.com/en-us/azure/azure-monitor/app/availability-overview
queries: []
