name: wafsg-UnusedAzureFirewallDeploymentsAzureFirewallInstances
title: Review under-utilized Azure Firewall instances. Identify and delete unused
  Azure Firewall deployments.
description: To identify unused Azure Firewall deployments, start by analyzing the
  monitoring metrics and UDRs associated with subnets pointing to the firewall's private
  IP. Combine that information with other validations, such as if your instance of
  Azure Firewall has any rules (classic) for NAT, Network and Application, or even
  if the DNS Proxy setting is configured to Disabled, and with internal documentation
  about your environment and deployments. You can detect deployments that are cost-effective
  over time.  For more information about monitoring logs and metrics, see Monitor
  Azure Firewall logs and metrics and SNAT port utilization.
source:
  type: wafsg
  file: ./checklists-ext/wafsg_checklist.en.json
resourceTypes:
- Microsoft.Network/azureFirewalls
waf: Cost
labels:
  guid: ef951ddc-d36a-4194-a039-48af1cd3b1dd
links: []
queries: {}
