guid: d4eb8667-f8cb-4cdd-94e6-2f967ba98f88
name: ApplicationGatewaySubnet-111
title: Filter inbound traffic in the backends so that they only accept connections
  from the Application Gateway subnet, for example with NSGs.
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
services:
- App Gateway
resourceTypes:
- microsoft.network/applicationGateways
waf: Security
severity: 1
labels: {}
links:
- https://learn.microsoft.com/azure/virtual-wan/scenario-secured-hub-app-gateway
queries: []
