guid: fa64b4dd-35c2-4047-ac5c-45dfbf8b0db9
name: ApplicationGateway
title: Use Application Gateway for native support for WebSocket and HTTP/2 protocols
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
services:
- App Gateway
resourceTypes:
- microsoft.network/applicationGateways
waf: Security
severity: 2
labels: {}
links:
- https://learn.microsoft.com/azure/application-gateway/application-gateway-websocket
queries: []
