guid: a4dd86d3-5ffa-408c-b660-cce073d085b8
name: AzureApplicationGatewayWaf
title: Tune the Azure Application Gateway WAF for your workload. Reduce false positive
  detections.
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
services:
- App Gateway
resourceTypes:
- microsoft.network/applicationGateways
waf: Security
severity: 0
labels: {}
links:
- https://learn.microsoft.com/azure/web-application-firewall/ag/best-practices#tune-your-waf
queries: []
