guid: 6c19dfd5-a61c-436c-9001-491b9b3d0228
name: LatestAzureApplicationGatewayWafRuleSetVersion
title: Use the latest Azure Application Gateway WAF rule set version. Rule set updates
  are regularly updated to take account of the current threat landscape.
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
services:
- App Gateway
resourceTypes:
- microsoft.network/applicationGateways
waf: Security
severity: 1
labels: {}
links:
- https://learn.microsoft.com/azure/web-application-firewall/ag/best-practices#use-the-latest-ruleset-versions
queries: []
reviewed: August 26, 2024
