name: revcl-PurviewAccountsArchitecturesDeploymentBestPractices
title: Follow Purview accounts architectures and deployment best practices
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
resourceTypes:
- Microsoft.Purview/accounts
waf: Reliability
severity: 1
labels:
  guid: 8cdc15ac-c075-4ee9-a130-a8889579e76b
links:
- type: docs
  url: https://learn.microsoft.com/purview/deployment-best-practices
queries: {}
