name: wafsg-JailbreakRiskDetectionLanguageModelDeployments
title: 'Protect integrity: Implement jailbreak risk detection to safeguard your language
  model deployments against prompt injection attacks.'
description: ''
source:
  type: wafsg
  file: well-architected/service-guides/azure-openai.md
  timestamp: July 24, 2024
resourceTypes:
- Microsoft.CognitiveServices/accounts
waf: Security
labels:
  guid: 41a12d3c-56b5-4f10-9eea-303af5adcdb6
links: []
queries: {}
