guid: 74d00018-ac6a-49e0-8e6a-83de5de32c19
name: ManagementGroupHierarchySettings
title: Enforce that only privileged users can operate management groups in the tenant
  by enabling Azure RBAC authorization in the management group hierarchy settings
source:
  type: revcl
  file: ./checklists/alz_checklist.en.json
resourceTypes: []
waf: Security
severity: 1
labels:
  alzArea: Resource Organization
  alzSubarea: Subscriptions
  alzId: C02.06
  checklist: alz
links:
- https://learn.microsoft.com/azure/governance/management-groups/how-to/protect-resource-hierarchy#setting---require-authorization
queries: []
reviewed: August 26, 2024
