guid: 5357ae22-0f52-1a49-9fd4-1f00ace6add0
name: WebApplicationFirewall
title: Monitor Web Application Firewall
description: |-
  Monitoring the health of your Web Application Firewall and the applications it protects is crucial. This can be achieved through integration with Microsoft Defender for Cloud, Azure Monitor, and Azure Monitor logs, ensuring optimal performance and security.
source:
  type: aprl
  file: azure-resources/Network/frontDoorWebApplicationFirewallPolicies/recommendations.yaml
  timestamp: July 24, 2024
services:
- Microsoft.Network/frontdoorWebApplicationFirewallPolicies
resourceTypes:
- Microsoft.Network/frontdoorWebApplicationFirewallPolicies
severity: 0
labels:
  area: Monitoring and Alerting
links: []
queries:
  arg: |
    // cannot-be-validated-with-arg
