name: aprl-BlobStorageAccountsCriticalApplications
title: Monitor all blob storage accounts
description: |-
  For critical applications and business processes relying on Azure, monitoring and alerts are crucial. Resource logs are only stored after creating a diagnostic setting to route logs to specified locations, requiring selection of log categories to collect.
source:
  type: aprl
  file: azure-resources/Storage/storageAccounts/recommendations.yaml
  timestamp: July 24, 2024
resourceTypes:
- Microsoft.Storage/storageAccounts
severity: 2
labels:
  guid: 96cb8331-6b06-8242-8ce8-4e2f665dc679
  area: Monitoring and Alerting
links: []
queries:
  arg: |
    // under-development
