name: revcl-AppServiceEnvironmentIsolatedEnvironment-1
title: If deploying to an Isolated environment, use or migrate to App Service Environment
  (ASE) v3
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
resourceTypes:
- microsoft.devices/provisioningservices
waf: Reliability
severity: 0
labels:
  guid: da0f033e-d180-4f36-9aa4-c468dba14203
links:
- type: docs
  url: https://learn.microsoft.com/en-us/azure/app-service/environment/intro
queries: {}
