guid: def7165b-3e46-4bab-b1a1-a24681c4cacc
name: DeploymentEnvironments
title: 'Meet capacity requirements: Choose deployment environments with autoscaling
  capabilities to add and remove capacity as demand fluctuates.'
description: ''
source:
  type: wafsg
  file: well-architected/service-guides/azure-machine-learning.md
  timestamp: July 24, 2024
services:
- Azure Machine Learning
resourceTypes:
- Microsoft.MachineLearningServices/workspaces
waf: Performance
labels: {}
links: []
queries: []
