guid: 0102ce16-ee30-41e6-b882-e52e4621dd68
name: ClusterConfiguration
title: Consider gitops to deploy applications or cluster configuration to multiple
  clusters
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
services:
- AKS
resourceTypes:
- microsoft.containerservice/managedClusters
waf: Operations
severity: 2
labels: {}
links:
- https://learn.microsoft.com/azure/architecture/example-scenario/bedrock/bedrock-automated-deployments
queries: []
