guid: e93bb813-b356-48f3-9bdf-a06a0a6ba039
name: SiteRecoveryVmFailoverSettings
title: Ensure static IP addresses in Site Recovery VM failover settings are available
  in failover subnet
description: Ensure VM failover settings' static IP addresses are available in the
  failover subnet to maintain consistent IP assignment during failover, with the target
  VM receiving the same static IP if it's available or the next available IP otherwise.
  IP adjustments can be made in VM Network settings.
source:
  type: aprl
  file: azure-resources/RecoveryServices/vaults/recommendations.yaml
  timestamp: July 24, 2024
services:
- Microsoft.RecoveryServices/vaults
resourceTypes:
- Microsoft.RecoveryServices/vaults
severity: 0
labels:
  area: Disaster Recovery
links: []
queries:
  arg: |-
    // cannot-be-validated-with-arg
