guid: 43e52f47-22d9-428c-8b1c-d521e54a29a9
name: FtaResiliencyPlaybook
title: FTA Resiliency Playbook
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
services:
- CosmosDB
resourceTypes:
- microsoft.documentdb/databaseAccounts
waf: Reliability
severity: 1
labels: {}
links:
- https://github.com/Azure/fta-resiliencyplaybooks/blob/main/pass-foundations-playbooks-CosmosDB_v1.docx
queries: []
