guid: 220c4ca6-6688-476b-b2b5-425a78e6fb87
name: WebApplicationFirewall-134
title: Use web application firewall (WAF) by deploying Application Gateway in front
  of APIM
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
services:
- APIM
resourceTypes:
- Microsoft.ApiManagement/service
waf: Security
severity: 0
labels: {}
links:
- https://learn.microsoft.com/security/benchmark/azure/baselines/api-management-security-baseline?toc=%2Fazure%2Fapi-management%2F&bc=%2Fazure%2Fapi-management%2Fbreadcrumb%2Ftoc.json#ns-6-deploy-web-application-firewall
queries: []
