guid: e6bfbb9e-d503-4547-ac44-7e826128a71f
name: AutomatedDeployments
title: For automated deployments,  request or reserve quota prior to starting the
  deployment
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
services:
- AVS
resourceTypes:
- Microsoft.AVS/privateClouds
waf: Operations
severity: 2
labels: {}
links: []
queries: []
reviewed: August 26, 2024
