name: revcl-LeverageFtaResiliencyPlaybookAzureDataFactory
title: Leverage FTA Resiliency Playbook for Azure Data Factory
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
resourceTypes:
- Microsoft.DataFactory/datafactories
waf: Reliability
severity: 1
labels:
  guid: ab91932c-9fc9-4d1b-a881-37f5e6c0cb9e
links:
- type: docs
  url: https://github.com/Azure/fta-resiliencyplaybooks/blob/main/paas-foundations-playbooks-ADF_v1.docx
queries: {}
