name: wafsg-AzureChaosStudioFaultLibrariesTestEnvironment
title: Build a test environment that closely matches your production environment to
  test updates and changes before you deploy them to production. Have processes in
  place to test the security updates, performance baselines, and reliability faults.
  Take advantage of Azure Chaos Studio fault libraries to inject and simulate error
  conditions. For more information, see Azure Chaos Studio fault and action library.
description: ''
source:
  type: wafsg
  file: well-architected/service-guides/virtual-machines.md
  timestamp: July 24, 2024
resourceTypes:
- Microsoft.Compute/virtualMachines
waf: Operations
labels:
  guid: bc5e266d-f8ee-4c9d-ba6c-edbb581c9a97
links: []
queries: {}
