name: wafsg-RegularSystemPatchingImmediatePatchApplication
title: Create a maintenance plan that includes regular system patching as a part of
  routine operations. Include emergency processes that allow for immediate patch application.
  You can have custom processes to manage patching or partially delegate the task
  to Azure.
description: ''
source:
  type: wafsg
  file: well-architected/service-guides/virtual-machines.md
  timestamp: July 24, 2024
resourceTypes:
- Microsoft.Compute/virtualMachines
waf: Operations
labels:
  guid: f419068c-ec1e-4c73-a7c6-ead478c8b4d6
links: []
queries: {}
