name: revcl-AzureApplicationGatewayWafPolicyBodyInspectionFeature
title: Enable request body inspection feature enabled in Azure Application Gateway
  WAF policy.
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
resourceTypes:
- microsoft.network/applicationGateways
waf: Security
severity: 0
labels:
  guid: 8ea8e0d4-84e8-4b33-aeab-493f6391b4d6
links:
- type: docs
  url: https://learn.microsoft.com/azure/web-application-firewall/ag/application-gateway-waf-request-size-limits#request-body-inspection
queries: {}
