name: revcl-LatestAzureApplicationGatewayWafRuleSetVersionRuleSetUpdates
title: Use the latest Azure Application Gateway WAF rule set version. Rule set updates
  are regularly updated to take account of the current threat landscape.
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
resourceTypes:
- microsoft.network/applicationgateways
waf: Security
severity: 1
labels:
  guid: 6c19dfd5-a61c-436c-9001-491b9b3d0228
links:
- type: docs
  url: https://learn.microsoft.com/azure/web-application-firewall/ag/best-practices#use-the-latest-ruleset-versions
queries: {}
