name: revcl-AzureApplicationGatewayWafRateLimitsHighRateLimitThresholds
title: 'Use a high threshold for Azure Application Gateway WAF rate limits. High rate
  limit thresholds avoid blocking legitimate traffic, while still providing protection
  against extremely high numbers of requests that might overwhelm your infrastructure. '
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
resourceTypes:
- microsoft.network/applicationgateways
waf: Security
severity: 1
labels:
  guid: 041e0ad8-7b12-4694-a0b7-a0e25ee2470f
links:
- type: docs
  url: https://learn.microsoft.com/azure/web-application-firewall/ag/rate-limiting-overview#rate-limiting-details
queries: {}
