name: revcl-ApplicationGatewaySubnetInboundTraffic
title: Filter inbound traffic in the backends so that they only accept connections
  from the Application Gateway subnet, for example with NSGs.
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
resourceTypes:
- microsoft.network/applicationgateways
waf: Security
severity: 1
labels:
  guid: d4eb8667-f8cb-4cdd-94e6-2f967ba98f88
links:
- type: docs
  url: https://learn.microsoft.com/azure/virtual-wan/scenario-secured-hub-app-gateway
queries: {}
