name: wafsg-NsgRestrictionsApplicationGateway
title: Comply with all NSG restrictions for Application Gateway
description: ''
source:
  type: wafsg
  file: well-architected/service-guides/azure-application-gateway.md
  timestamp: July 24, 2024
resourceTypes:
- microsoft.network/applicationgateways
waf: Security
severity: 1
labels:
  guid: 12e359f5-1252-4fdf-83e8-542e5d5d34d8
links: []
queries: {}
