name: wafsg-ApplicationGatewaySubnetUserDefinedRoutes
title: Refrain from using UDRs on the Application gateway subnet
description: Using User Defined Routes (UDR) on the Application Gateway subnet can
  cause some issues. Health status in the back-end might be unknown. Application Gateway
  logs and metrics might not get generated. We recommend that you don't use UDRs on
  the Application Gateway subnet so that you can view the back-end health, logs, and
  metrics. If your organizations require to use UDR in the Application Gateway subnet,
  please ensure you review the supported scenarios. For more information, see Supported
  user-defined routes.
source:
  type: wafsg
  file: ./checklists-ext/wafsg_checklist.en.json
resourceTypes:
- microsoft.network/applicationgateways
waf: Security
severity: 1
labels:
  guid: 9ba32fa7-9880-47f8-aaed-93097fe35c99
links: []
queries: {}
