name: wafsg-LatestTlsPolicyVersionEnhancedSecurity
title: Set up a TLS policy for enhanced security
description: Set up a TLS policy for extra security. Ensure you're always using the
  latest TLS policy version available. This enforces TLS 1.2 and stronger ciphers.
source:
  type: wafsg
  file: ./checklists-ext/wafsg_checklist.en.json
resourceTypes:
- microsoft.network/applicationGateways
waf: Security
labels:
  guid: 7547ed98-86fb-4a8f-94d8-162c5d6fd39d
links: []
queries: {}
