name: wafsg-RequireSecureTransferSettingStandardDataProcessingRates
title: NFS Azure file shares are only accessible through restricted networks. So you
  must create a private endpoint for your storage account or restrict public endpoint
  access to selected virtual networks and IP addresses. We recommend that you create
  a private endpoint. You must configure network-level security for NFS shares because
  Azure Files doesn't support encryption in transit with the NFS protocol. You need
  to disable the Require secure transfer setting on the storage account to use NFS
  Azure file shares. Standard data processing rates apply for private endpoints. If
  you don't require a static IP address for your file share and want to avoid the
  cost of private endpoints, you can restrict public endpoint access instead.
description: Network traffic travels over the Microsoft backbone network instead of
  the public internet, which eliminates risk exposure from the public internet.
source:
  type: wafsg
  file: ./checklists-ext/wafsg_checklist.en.json
resourceTypes:
- microsoft.storage/storageaccounts
waf: Security
severity: 1
labels:
  guid: 8959f137-e162-4b86-a14f-6e96c9fd5494
links: []
queries: {}
