name: wafsg-StorageAccountKeyAccessSmbSecuritySettings
title: If you use storage account keys, store them in Key Vault, and make sure to
  regenerate them periodically. You can completely disallow storage account key access
  to the file share by removing NTLMv2 from the share's SMB security settings. But
  you generally shouldn't remove NTLMv2 from the share's SMB security settings because
  administrators still need to use the account key for some tasks.
description: Use Key Vault to retrieve keys at runtime instead of saving them with
  your application. Key Vault also makes it easy to rotate your keys without interruption
  to your applications. Periodically rotate the account keys to reduce the risk of
  exposing your data to malicious attacks.
source:
  type: wafsg
  file: ./checklists-ext/wafsg_checklist.en.json
resourceTypes:
- microsoft.storage/storageaccounts
waf: Security
severity: 1
labels:
  guid: c034b5bc-eaca-4ba4-b9c7-3d427108584d
links: []
queries: {}
