guid: 56195bba-5bc2-4f00-976e-f2734b46fe2b
name: UseApplicationGateway
title: Use Application Gateway with Web Application Firewall (WAF) within a virtual
  network to protect inbound `HTTP/S` traffic from the Internet.
description: ''
source:
  type: wafsg
  file: well-architected/service-guides/azure-application-gateway.md
  timestamp: July 24, 2024
services:
- Azure Application Gateway
resourceTypes:
- microsoft.network/applicationGateways
waf: Reliability
labels: {}
links: []
queries: []
