name: revcl-AksHttpRoutingAddApplicationRouting
title: Do not use AKS HTTP Routing Add-On, use instead the managed NGINX ingress with
  the application routing add-on.
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
resourceTypes:
- microsoft.containerservice/managedClusters
waf: Reliability
severity: 0
labels:
  guid: 8008ae7d-7e4b-4475-a6c8-bdbf59bce65d
links:
- type: docs
  url: https://learn.microsoft.com/azure/aks/http-application-routing
queries:
  arg: where type=='microsoft.containerservice/managedclusters' | extend compliant
    = (isnull(properties.addonProfiles.httpApplicationRouting) or properties.addonProfiles.httpApplicationRouting.enabled==false)
    | distinct id,compliant
