name: wafsg-RegularVmssBasedAksDeploymentSeparateDataCenters
title: 'Cluster architecture: Use availability zones to maximize resilience within
  an Azure region by distributing AKS agent nodes across physically separate data
  centers.'
description: By spreading node pools across multiple zones, nodes in one node pool
  will continue running even if another zone has gone down. If colocality requirements
  exist, either a regular VMSS-based AKS deployment into a single zone or proximity
  placement groups can be used to minimize internode latency.
source:
  type: wafsg
  file: ./checklists-ext/wafsg_checklist.en.json
resourceTypes:
- microsoft.containerservice/managedClusters
waf: Reliability
labels:
  guid: 4834a7a7-6bf7-4a58-961b-f1b97da3c724
links: []
queries: {}
