name: wafsg-ApplicationDeploymentManifestsPodResourceRequests
title: 'Cluster and workload architectures: Define Pod resource requests and limits
  in application deployment manifests, and enforce with Azure Policy.'
description: Container CPU and memory resource limits are necessary to prevent resource
  exhaustion in your Kubernetes cluster.
source:
  type: wafsg
  file: ./checklists-ext/wafsg_checklist.en.json
resourceTypes:
- microsoft.containerservice/managedClusters
waf: Reliability
labels:
  guid: 5527c666-0096-4a1d-9022-cada9d4c77da
links: []
queries: {}
