guid: 06194a9a-646b-40f8-81df-2cffae089d7b
name: UnderlyingDiskConfiguration
title: 'Optimize for hybrid deployments: If you use Azure File Sync, sync performance
  depends on many factors: your Windows Server and the underlying disk configuration,
  network bandwidth between the server and the Azure storage, file size, total dataset
  size, and the activity on the dataset. To measure the performance of a solution
  that''s based on Azure File Sync, determine the number of objects, such as files
  and directories, that you process per second.'
description: ''
source:
  type: wafsg
  file: well-architected/service-guides/azure-files.md
  timestamp: July 24, 2024
services:
- Azure Files
resourceTypes:
- Microsoft.Storage/storageAccounts
waf: Performance
labels: {}
links: []
queries: []
