guid: 18c8b61c-855a-4405-b6ed-266455e4f4ce
name: SapApplicationServerLayer
title: It is NOT supported at all to run an SAP Application Server layer and DBMS
  layer split between on-premise and Azure. Both layers need to completely reside
  either on-premise or in Azure.
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
services:
- SAP
resourceTypes: []
waf: Performance
severity: 0
labels: {}
links:
- https://me.sap.com/notes/2015553
- https://learn.microsoft.com/azure/cloud-adoption-framework/scenarios/sap/eslz-network-topology-and-connectivity
queries: []
