guid: f82cb8eb-8c0a-4a63-a25a-4956eaa8dc4a
name: ExternalApplication
title: Use an external application such as kubecost to allocate costs to different
  users
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
services:
- AKS
resourceTypes:
- microsoft.containerservice/managedClusters
waf: Cost
severity: 2
labels: {}
links:
- https://learn.microsoft.com/azure/cloud-adoption-framework/scenarios/aks/eslz-cost-governance-with-kubecost
queries: []
