name: aprl-AppConfigurationStandardTierFreeTier
title: Upgrade to App Configuration Standard tier
description: |-
  SLA is not available for Free tier. Upgrade to the Standard tier to get an SLA of 99.9%
source:
  type: aprl
  file: azure-resources/AppConfiguration/configurationStores/recommendations.yaml
  timestamp: July 24, 2024
resourceTypes:
- Microsoft.AppConfiguration/configurationStores
severity: 0
labels:
  guid: 2102a57a-a056-4d5e-afe5-9df9f92177ca
  area: High Availability
links: []
queries:
  arg: |-
    // Azure Resource Graph Query
    // Upgrade to App Configuration Standard tier
    resources
    | where type =~ "Microsoft.AppConfiguration/configurationStores"
    | where sku.name == "free"
    | project recommendationId = "2102a57a-a056-4d5e-afe5-9df9f92177ca", name, id, tags, param1 = "Upgrade to Standard SKU"
