name: revcl-DiagnosticsSettingsAzureMonitor
title: Enable Diagnostics Settings to export logs to Azure Monitor
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
resourceTypes:
- microsoft.apimanagement/service
waf: Operations
severity: 0
labels:
  guid: a7d0840a-c8c4-4e83-adec-5ca578eb4049
links:
- type: docs
  url: https://learn.microsoft.com/azure/api-management/api-management-howto-use-azure-monitor#resource-logs
queries: {}
