guid: 7947e534-c9a8-435b-9e03-d300143b5f74
name: ApplicationGatewayInstances-292
title: Review underutilized resources
description: Identify and delete Application Gateway instances with empty backend
  pools to avoid unnecessary costs.
source:
  type: revcl
  file: ./checklists-ext/wafsg_checklist.en.json
services:
- Azure Application Gateway
resourceTypes:
- microsoft.network/applicationGateways
waf: Cost
labels: {}
links: []
queries: []
reviewed: August 26, 2024
