guid: 62ea8582-63cb-4ac6-8a73-c800a2a0428a
name: WebApplication
title: 'Review the performance antipatterns: To make sure the web application performs
  and scales in accordance with your business requirements, avoid the typical antipatterns.
  Here are some antipatterns that App Service corrects.'
description: ''
source:
  type: wafsg
  file: well-architected/service-guides/app-service-web-apps.md
  timestamp: July 24, 2024
services:
- App Service Web Apps
resourceTypes:
- Microsoft.Web/sites
waf: Performance
labels: {}
links: []
queries: []
