guid: 4e2a03a6-ff51-46c5-902d-3d7161d9c99c
name: EnvironmentCosts
title: 'Optimize environment costs: Consider the Basic or Free tier to run pre-production
  environments. These tiers are low performance and low cost. If you use the Basic
  or Free tier, use governance to enforce the tier, constrain the number of instances
  and CPUs, restrict scaling, and limit log retention.'
description: ''
source:
  type: wafsg
  file: well-architected/service-guides/app-service-web-apps.md
  timestamp: July 24, 2024
services:
- App Service Web Apps
resourceTypes:
- Microsoft.Web/sites
waf: Cost
labels: {}
links: []
queries: []
