guid: 41026085-4728-4bff-abbe-be08a46e4735
name: SameComputeEnvironment
title: 'Optimize deployment costs: Take advantage of deployment slots to optimize
  costs. The slot runs in the same compute environment as the production instance.
  Use them strategically for scenarios like blue-green deployments that switch between
  slots. This approach minimizes downtime and ensures smooth transitions.'
description: ''
source:
  type: wafsg
  file: well-architected/service-guides/app-service-web-apps.md
  timestamp: July 24, 2024
services:
- App Service Web Apps
resourceTypes:
- Microsoft.Web/sites
waf: Cost
labels: {}
links: []
queries: []
