guid: 87585797-5551-4d53-bb7d-a94ee415734d
name: ExistingAzureEnvironment
title: For SAP RISE/ECS deployments, virtual peering is the preferred way to establish
  connectivity with customer's existing Azure environment. Both the SAP vnet and customer
  vnet(s) are protected with network security groups (NSG), enabling communication
  on SAP and database ports through the vnet peering
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
services:
- SAP
resourceTypes: []
waf: Security
severity: 1
labels: {}
links:
- https://learn.microsoft.com/azure/sap/workloads/rise-integration
queries: []
