name: revcl-NatGatewaySettingsSnatPortUsage
title: "Prevent SNAT Port exhaustion by monitoring SNAT port usage, evaluating NAT\
  \ Gateway settings, and ensuring seamless failover. If the port count approaches\
  \ the limit, it\u2019s a sign that SNAT exhaustion might be imminent."
source:
  type: revcl
  file: ./checklists/alz_checklist.en.json
resourceTypes:
- Microsoft.Network/azureFirewalls
waf: Performance
severity: 1
labels:
  guid: 7371dc21-251a-47a3-af14-6e01b9da4757
  area: Network Topology and Connectivity
  subarea: Firewall
  id: D07.14
links:
- type: docs
  url: https://learn.microsoft.com/azure/nat-gateway/tutorial-hub-spoke-nat-firewall
queries: {}
