name: aprl-ResourceManagerTemplatesAutomatedDeploymentUpdateProcess
title: Store configuration as app settings
description: |-
  Use app settings for configuration and define them in Resource Manager templates or via PowerShell to facilitate part of an automated deployment/update process for improved reliability.
source:
  type: aprl
  file: azure-resources/Web/sites/recommendations.yaml
  timestamp: July 24, 2024
resourceTypes:
- Microsoft.Web/sites
severity: 1
labels:
  guid: 0b80b67c-afbe-4988-ad58-a85a146b681e
  area: Other Best Practices
links: []
queries:
  arg: |
    // Azure Resource Graph Query
    // Provides a list of Azure App Service resources that don't have App Settings configured

    appserviceresources
    | where type == "microsoft.web/sites/config"
    | extend AppSettings = iif(isempty(properties.AppSettings), true, false)
    | where AppSettings == false
    | project  recommendationId="0b80b67c-afbe-4988-ad58-a85a146b681e", id, name, tags="", param1="AppSettings is not configured"
