name: wafsg-MicrosoftSentinelSolutionsAzureNetworkSecurity
title: Configure Azure Firewall integration with Microsoft Defender for Cloud and
  Microsoft Sentinel.
description: If these tools are available in the environment, it is recommended to
  leverage integration with Microsoft Defender for Cloud and Microsoft Sentinel solutions.
  With Microsoft Defender for Cloud integration, you can visualize the all-up status
  of network infrastructure and network security in one place, including Azure Network
  Security across all VNets and Virtual Hubs spread across different regions in Azure.
  Integration with Microsoft Sentinel provides threat detection and prevention capabilities.
source:
  type: wafsg
  file: ./checklists-ext/wafsg_checklist.en.json
resourceTypes:
- Microsoft.Network/azureFirewalls
waf: Operations
labels:
  guid: e900c615-4865-4658-8cba-0d0f5fb6d169
links: []
queries: {}
