name: aprl-NodePoolAutoScaleSettingsNodePoolSettings
title: Node pool auto-scale settings should not exceed subscription core quota
description: |-
  Node pool settings should not exceed the subscription core quota to ensure AKS can scale out nodes efficiently, meeting increased demand while reducing resource constraints and potential service disruptions.
source:
  type: aprl
  file: azure-resources/ContainerService/managedClusters/recommendations.yaml
  timestamp: July 24, 2024
resourceTypes:
- Microsoft.ContainerService/managedClusters
severity: 0
labels:
  guid: a01afc4c-7439-4919-b2da-3565992ea2a7
  area: High Availability
links: []
queries:
  arg: |-
    // cannot-be-validated-with-arg
