guid: e7d7e484-3276-4d8b-bc05-5bcf619e8a13
name: AzureAutomanageMachineConfigurationAuditCapabilities
title: Monitor OS level virtual machine (VM) configuration drift using Azure Policy.
  Enabling Azure Automanage Machine Configuration audit capabilities through policy
  helps application team workloads to immediately consume feature capabilities with
  little effort.
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
services:
- VM
resourceTypes:
- Microsoft.Compute/virtualMachines
waf: Operations
severity: 1
labels: {}
links:
- https://learn.microsoft.com/azure/governance/machine-configuration/overview
- https://learn.microsoft.com/learn/paths/implement-resource-mgmt-security/
queries: []
