guid: 80693bc5-79bf-4928-8887-1a77544d3bad
name: WebApplicationFirewall-139
title: 'Workload architecture: Use a Web Application Firewall to secure HTTP(S) traffic.'
description: ''
source:
  type: wafsg
  file: well-architected/service-guides/azure-kubernetes-service.md
  timestamp: July 24, 2024
services:
- Azure Kubernetes Service
resourceTypes:
- microsoft.containerservice/managedClusters
waf: Security
labels: {}
links: []
queries: []
