guid: 2586b854-237e-47f1-84a1-d45d4cd2310d
name: IacDeployments
title: Make sure that your IaC deployments are configuring label-based propagation
  in Virtual WAN, otherwise connectivity between virtual hubs will be impaired.
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
services:
- VWAN
resourceTypes:
- microsoft.network/virtualWans
waf: Reliability
severity: 1
labels: {}
links:
- https://learn.microsoft.com/azure/virtual-wan/about-virtual-hub-routing#labels
queries: []
