guid: 727c77e1-b9aa-4a37-a024-129d042422c1
name: IacDeployments-558
title: Make sure that your IaC deployments does not disable branch-to-branch traffic
  in Virtual WAN, unless these flows should be explicitly blocked.
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
services:
- VWAN
resourceTypes:
- microsoft.network/virtualWans
waf: Reliability
severity: 1
labels: {}
links:
- https://learn.microsoft.com/azure/virtual-wan/virtual-wan-faq#is-branch-to-branch-connectivity-allowed-in-virtual-wan
queries: []
reviewed: August 26, 2024
