guid: 4ed59aaa-9948-4387-975e-11e1fc65ff40
name: TransportLayerSecurity
title: 'Encrypt data: Protect data in transit with end-to-end Transport Layer Security
  (TLS). Use your customer-managed keys for full encryption of data at rest. For more
  information, see Encryption at rest using customer-managed keys.'
description: ''
source:
  type: wafsg
  file: well-architected/service-guides/app-service-web-apps.md
  timestamp: July 24, 2024
services:
- App Service Web Apps
resourceTypes:
- Microsoft.Web/sites
waf: Security
labels: {}
links: []
queries: []
