guid: 0d13edb5-8966-463a-868e-c3ba9d94e644
name: Multi-RegionDeploymentTopology
title: 'Resiliency: Deploy models to environments that support availability zones,
  such as AKS. By ensuring deployments are distributed across availability zones,
  you''re ensuring a deployment is available even in the event of a datacenter failure.
  For enhanced reliability and availability, consider a multi-region deployment topology.'
description: ''
source:
  type: wafsg
  file: well-architected/service-guides/azure-machine-learning.md
  timestamp: July 24, 2024
services:
- Azure Machine Learning
resourceTypes:
- Microsoft.MachineLearningServices/workspaces
waf: Reliability
labels: {}
links: []
queries: []
