guid: 3f9bcbd4-6826-46ab-aa26-4f9a19aed9c5
name: DevopsDeploymentPipeline
title: Deploy from a trusted environment
description: Deploy code to App Service from a controlled and trusted environment,
  like a well-managed and secured DevOps deployment pipeline. This avoids code that
  was not version controlled and verified to be deployed from a malicious host.
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
services:
- App Services
resourceTypes:
- microsoft.web/sites
waf: Security
severity: 0
labels: {}
links:
- https://learn.microsoft.com/azure/app-service/deploy-best-practices
queries: []
