guid: 475ba18f-dbf5-490c-b65d-e8e03f9bcbd4
name: HttpStrictTransportSecurity
title: Use HTTPS only
description: Configure App Service to use HTTPS only.  This causes App Service to
  redirect from HTTP to HTTPS.  Strongly consider the use of HTTP Strict Transport
  Security (HSTS) in your code or from your WAF, which informs browsers that the site
  should only be accessed using HTTPS.
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
services:
- App Services
resourceTypes:
- microsoft.web/sites
waf: Security
severity: 0
labels: {}
links:
- https://learn.microsoft.com/azure/app-service/configure-ssl-bindings#enforce-https
queries:
  arg: where (type=='microsoft.web/sites' and (kind == 'app' or kind == 'app,linux'
    )) | extend compliant = (properties.httpsOnly==true) | distinct id,compliant
