name: revcl-RequiredServicesDeploymentRegions
title: Ensure required services and features are available within the chosen deployment
  regions eg. ANF , Zone etc.
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
resourceTypes: []
waf: Operations
severity: 0
labels:
  guid: e6e20617-3686-4af4-9791-f8935ada4332
links:
- type: docs
  url: https://azure.microsoft.com/explore/global-infrastructure/products-by-region/
- type: docs
  url: https://learn.microsoft.com/azure/cloud-adoption-framework/migrate/azure-best-practices/multiple-regions?source=recommendations
queries: {}
