name: revcl-MicrosoftEntraIdConditionalAccessPoliciesAzureEnvironments
title: Enforce Microsoft Entra ID conditional-access policies for any user with rights
  to Azure environments
source:
  type: revcl
  file: ./checklists/alz_checklist.en.json
resourceTypes:
- Microsoft.AAD/domainServices
waf: Security
severity: 2
labels:
  guid: 53e8908a-e28c-484c-93b6-b7808b9fe5c4
  area: Identity and Access Management
  subarea: Identity
  id: B03.04
links:
- type: docs
  url: https://learn.microsoft.com/azure/active-directory/conditional-access/overview
- type: docs
  url: https://learn.microsoft.com/learn/modules/plan-implement-administer-conditional-access/
queries: {}
