name: revcl-MicrosoftEntraIdApplicationProxyRemoteUsers
title: Where required, use Microsoft Entra ID Application Proxy to give remote users
  secure and authenticated access to internal applications (hosted in the cloud or
  on-premises).
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
resourceTypes:
- microsoft.aad/domainservices
waf: Security
severity: 1
labels:
  guid: d5d1e4e6-1465-48d3-958f-d77249b82111
links:
- type: docs
  url: https://learn.microsoft.com/azure/active-directory/app-proxy/application-proxy
- type: docs
  url: https://learn.microsoft.com/learn/paths/implement-applications-external-access-azure-ad/
queries: {}
