name: revcl-MicrosoftEntraIdApplicationProxyAzureVirtualDesktop
title: If users only need access to internal applications, has Microsoft Entra ID
  Application Proxy been considered as an alternative to Azure Virtual Desktop (AVD)?
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
resourceTypes:
- Microsoft.AAD/domainServices
waf: Security
severity: 2
labels:
  guid: 3b4b3e88-a459-4ed5-a22f-644dfbc58204
links:
- type: docs
  url: https://learn.microsoft.com/azure/active-directory/app-proxy/application-proxy#how-application-proxy-works
- type: docs
  url: https://learn.microsoft.com/learn/modules/configure-azure-ad-application-proxy/
queries: {}
