name: wafsg-ThresholdSettingsHealthProbes
title: Review the impact of the interval and threshold settings on health probes
description: ''
source:
  type: wafsg
  file: well-architected/service-guides/azure-application-gateway.md
  timestamp: July 24, 2024
resourceTypes:
- microsoft.network/applicationGateways
waf: Reliability
labels:
  guid: 9754bccf-e2a5-4b36-9bca-058ec0a08fff
links: []
queries: {}
