name: wafsg-ApplicationGatewayBackendPool
title: Plan for rule updates
description: Plan enough time for updates before accessing Application Gateway or
  making further changes. For example, removing servers from backend pool might take
  some time because they have to drain existing connections.
source:
  type: wafsg
  file: ./checklists-ext/wafsg_checklist.en.json
resourceTypes:
- microsoft.network/applicationGateways
waf: Reliability
labels:
  guid: 67b006ed-a8b2-4f66-806b-ed9d83f94982
links: []
queries: {}
