name: revcl-ApplicationDeliveryServicesAzureFrontDoor
title: Add diagnostic settings to save WAF logs from application delivery services
  like Azure Front Door and Azure Application Gateway. Regularly review the logs to
  check for attacks and for false positive detections.
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
resourceTypes:
- microsoft.network/frontdoorwebapplicationfirewalls
waf: Operations
severity: 0
labels:
  guid: 89cc5e11-aa4d-4c3b-893d-feb99215266a
links:
- type: docs
  url: https://learn.microsoft.com/azure/web-application-firewall/afds/waf-front-door-best-practices#add-diagnostic-settings-to-save-your-wafs-logs
queries: {}
