name: revcl-AzureFrontDoorMultiRegionDeployment
title: Use Azure Front Door in front of APIM for multi-region deployment
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
resourceTypes:
- microsoft.apimanagement/service
waf: Performance
severity: 1
labels:
  guid: 7519e385-a88b-4d34-966b-6269d686e890
links:
- type: docs
  url: https://learn.microsoft.com/azure/api-management/front-door-api-management
queries: {}
