guid: b9b140cf-413a-483d-aad2-8802c4e3c017
name: SapApplicationServer
title: Review SAP application server to database server latency using SAP ABAPMeter
  report /SSA/CAT.
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
services:
- SAP
resourceTypes: []
waf: Performance
severity: 1
labels: {}
links:
- https://techcommunity.microsoft.com/t5/running-sap-applications-on-the/sap-on-azure-general-update-march-2019/ba-p/377456
- https://me.sap.com/notes/0002879613
queries: []
reviewed: August 26, 2024
