guid: 060c6964-52b5-48db-af8b-83e4b2d85349
name: ApplicationGateway-107
title: Deploy Application Gateway across Availability Zones
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
services:
- App Gateway
resourceTypes:
- microsoft.network/applicationGateways
waf: Reliability
severity: 1
labels: {}
links:
- https://learn.microsoft.com/azure/reliability/migrate-app-gateway-v2
- https://learn.microsoft.com/learn/paths/secure-application-delivery/
queries:
  arg: resources | where type =~ 'microsoft.network/applicationGateways' | extend
    compliant = (isnotnull(zones) and array_length(zones) > 1) | distinct id,compliant
reviewed: August 26, 2024
