name: wafsg-AzureFirewallDnsProxyConfigurationFullyQualifiedDomainName
title: Use Fully Qualified Domain Name (FQDN) filtering in network rules.
description: You can use FQDN based on DNS resolution in Azure Firewall and firewall
  policies. This capability allows you to filter outbound traffic with any TCP/UDP
  protocol (including NTP, SSH, RDP, and more). You must enable the Azure Firewall
  DNS Proxy configuration to use FQDNs in your network rules. To learn how it works,
  see Azure Firewall FQDN filtering in network rules.
source:
  type: wafsg
  file: ./checklists-ext/wafsg_checklist.en.json
resourceTypes:
- Microsoft.Network/azureFirewalls
waf: Security
labels:
  guid: edad73e6-11f4-4f3d-ad4d-85a803631d88
links: []
queries: {}
