name: wafsg-VirtualWanScenariosZeroTrustConfigurationGuide
title: Review Zero-Trust configuration guide for Azure Firewall and Application Gateway
description: If your security requirements necessitate implementing a Zero-Trust approach
  for web applications (inspection and encryption), it is recommended to follow this
  guide. In this document, how to integrate together Azure Firewall and Application
  Gateway will be explained, in both traditional Hub & Spoke and Virtual WAN scenarios.
source:
  type: wafsg
  file: ./checklists-ext/wafsg_checklist.en.json
resourceTypes:
- Microsoft.Network/azureFirewalls
waf: Security
labels:
  guid: 96522d15-f2d0-41d0-b021-c87b47bf8b59
links: []
queries: {}
