guid: 9cf5418b-1520-4b7b-add7-88eb28f833e8
name: ApplicationLandingZone
title: Configure Identity network segmentation through the use of a virtual Network
  and peer back to the hub. Providing authentication inside application landing zone
  (legacy).
source:
  type: revcl
  file: ./checklists/alz_checklist.en.json
resourceTypes: []
waf: Security
severity: 1
labels:
  alzArea: Identity and Access Management
  alzSubarea: Landing zones
  alzId: B04.01
  checklist: alz
links:
- https://learn.microsoft.com/azure/cloud-adoption-framework/ready/landing-zone/design-area/identity-access-landing-zones#managed-identities
- https://learn.microsoft.com/azure/architecture/example-scenario/identity/adds-extend-domain
queries: []
