name: aprl-AzureSqlDatabaseDatabaseLayerConfiguration
title: Implement Retry Logic
description: |-
  During transient failures, the application should handle connection retries effectively with Azure SQL Database. No Database layer configuration is needed; instead, the application must be set up for graceful retrying.
source:
  type: aprl
  file: azure-resources/Sql/servers/recommendations.yaml
  timestamp: July 24, 2024
resourceTypes:
- Microsoft.Sql/servers
severity: 0
labels:
  guid: cbb17a29-64fb-c943-95d0-8df814a37c40
  area: High Availability
links: []
queries:
  arg: |
    // cannot-be-validated-with-arg
