guid: 6f1432ef-61d2-4037-8f85-58e005d16b8c
name: AzureApplicationGateway
title: Familiarize yourself with Application Gateway pricing
description: For information about Application Gateway pricing, see Understanding
  Pricing for Azure Application Gateway and Web Application Firewall. You can also
  leverage the Pricing calculator.Ensure that the options are adequately sized to
  meet the capacity demand and deliver expected performance without wasting resources.
source:
  type: revcl
  file: ./checklists-ext/wafsg_checklist.en.json
services:
- Azure Application Gateway
resourceTypes:
- microsoft.network/applicationGateways
waf: Cost
labels: {}
links: []
queries: []
