name: wafsg-LastSynchronizationTimePropertyGzrsConfigurations-1
title: Before you initiate a failover or failback, check the value of the last synchronization
  time property to evaluate the potential for data loss. This recommendation applies
  only to GRS and GZRS configurations.
description: This property helps you estimate how much data you might lose if you
  initiate an account failover. All data and metadata that's written before the last
  synchronization time is available on the secondary region, but you might lose data
  and metadata that's written after the last synchronization time because it's not
  written to the secondary region.
source:
  type: wafsg
  file: ./checklists-ext/wafsg_checklist.en.json
resourceTypes:
- microsoft.storage/storageaccounts
waf: Reliability
severity: 1
labels:
  guid: f436bbde-bfd0-4be2-85a6-c13f0d79cee1
links: []
queries: {}
