name: wafsg-GzrsConfigurationOptionsDifferentAvailabilityZones
title: Configure your account for redundancy. For maximum availability and durability,
  configure your account by using zone-redundant storage (ZRS) or GZRS.
description: Redundancy protects your data against unexpected failures. The ZRS and
  GZRS configuration options replicate across different availability zones and enable
  applications to continue reading data during an outage. For more information, see
  Durability and availability by outage scenario and Durability and availability parameters.
source:
  type: wafsg
  file: ./checklists-ext/wafsg_checklist.en.json
resourceTypes:
- microsoft.storage/storageaccounts
waf: Reliability
severity: 1
labels:
  guid: 0a6a14f8-c014-4339-a444-45013d989209
links: []
queries: {}
