name: wafsg-LastSynchronizationTimePropertyGzrsConfigurations
title: Before initiating a failover or failback, evaluate the potential for data loss
  by checking the value of the last synchronization time property. This recommendation
  applies only to GRS and GZRS configurations.
description: This property helps you estimate how much data you might lose by initiating
  an account failover. All data and metadata written before the last synchronization
  time is available on the secondary region, but data and metadata written after the
  last synchronization time might be lost because it's not written to the secondary
  region.
source:
  type: wafsg
  file: ./checklists-ext/wafsg_checklist.en.json
resourceTypes:
- Microsoft.Storage/storageAccounts
waf: Reliability
labels:
  guid: af07c8fb-ba63-41e5-b924-3bc6759ad671
links: []
queries: {}
