guid: 919ca0b2-c121-459e-814b-933df574eccc
name: AuthenticatedWebApplication
title: Use an established Identity Provider for authentication
description: For authenticated web application, use a well established Identity Provider
  like Azure AD or Azure AD B2C.  Leverage the application framework of your choice
  to integrate with this provider or use the App Service Authentication / Authorization
  feature.
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
services:
- App Services
resourceTypes:
- microsoft.web/sites
waf: Security
severity: 1
labels: {}
links:
- https://learn.microsoft.com/azure/app-service/overview-authentication-authorization
queries: []
reviewed: August 26, 2024
