name: wafsg-ApplicationGatewayInstancesExtraneousCosts
title: Stop Application Gateway instances when not in use
description: You aren't billed when Application Gateway is in the stopped state. Continuously
  running Application Gateway instances can incur extraneous costs. Evaluate usage
  patterns and stop instances when you don't need them. For example, usage after business
  hours in Dev/Test environments is expected to be low.See these articles for information
  about how to stop and start instances.- Stop-AzApplicationGateway- Start-AzApplicationGateway
source:
  type: wafsg
  file: ./checklists-ext/wafsg_checklist.en.json
resourceTypes:
- microsoft.network/applicationgateways
waf: Cost
severity: 1
labels:
  guid: 3c5f0966-3c57-4e15-a6b0-6cb73405bbf1
links: []
queries: {}
