name: wafsg-AzureApplicationGatewayWebApplicationFirewall
title: Familiarize yourself with Application Gateway pricing
description: For information about Application Gateway pricing, see Understanding
  Pricing for Azure Application Gateway and Web Application Firewall. You can also
  leverage the Pricing calculator.Ensure that the options are adequately sized to
  meet the capacity demand and deliver expected performance without wasting resources.
source:
  type: wafsg
  file: ./checklists-ext/wafsg_checklist.en.json
resourceTypes:
- microsoft.network/applicationgateways
waf: Cost
severity: 1
labels:
  guid: 6f1432ef-61d2-4037-8f85-58e005d16b8c
links: []
queries: {}
