name: revcl-TrustedEnvironmentPrivateEndpoint
title: Deploy images from a trusted environment
description: Deploy container images to an ACR behind a Private endpoint within a
  trusted network
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
resourceTypes:
- microsoft.containerregistry/registries
waf: Security
severity: 0
labels:
  guid: b3bec3d4-f343-47c1-936d-b55f27a71eee
links: []
queries: {}
