name: wafsg-ApplicationGatewayHighTrafficSupportApplicationGatewayCapacity
title: Monitor capacity metrics
description: Use these metrics as indicators of utilization of the provisioned Application
  Gateway capacity. We strongly recommend setting up alerts on capacity. For details,
  see Application Gateway high traffic support.
source:
  type: wafsg
  file: ./checklists-ext/wafsg_checklist.en.json
resourceTypes:
- microsoft.network/applicationgateways
waf: Operations
severity: 1
labels:
  guid: 14cdf40e-36a1-4947-90a3-3b833e2df9d3
links: []
queries: {}
