name: wafsg-WebApplicationFirewallApplicationGateway
title: Enable diagnostics on Application Gateway and Web Application Firewall (WAF)
description: ''
source:
  type: wafsg
  file: well-architected/service-guides/azure-application-gateway.md
  timestamp: July 24, 2024
resourceTypes:
- microsoft.network/applicationGateways
waf: Operations
labels:
  guid: 63eb295f-ef20-4749-a576-fbbdd528d093
links: []
queries: {}
