name: revcl-PreferredLogManagementSolutionViaDiagnosticSettings
title: Send master logs (aka API logs) to Azure Monitor or your preferred log management
  solution
description: Via Diagnostic Settings at the cluster level
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
resourceTypes:
- microsoft.containerservice/managedClusters
waf: Operations
severity: 2
labels:
  guid: 5b56ad48-408f-4e72-934c-476ba280dcf5
links:
- type: docs
  url: https://learn.microsoft.com/azure/aks/monitor-aks
queries: {}
