name: wafsg-SeamlessOnboardingExperienceReferenceConfigureScraping
title: 'Workload architecture: Configure scraping of Prometheus metrics with Container
  insights.'
description: Container insights, which are part of Azure Monitor, provide a seamless
  onboarding experience to collect Prometheus metrics. Reference Configure scraping
  of Prometheus metrics for more information.
source:
  type: wafsg
  file: ./checklists-ext/wafsg_checklist.en.json
resourceTypes:
- microsoft.containerservice/managedclusters
waf: Operations
severity: 1
labels:
  guid: 35367a45-61fb-4731-a636-e59e8ce67fac
links: []
queries: {}
