name: wafsg-CentralizedConsistentMannerPodsConfigurationStandards
title: 'Cluster architecture: Operationalize clusters and pods configuration standards
  with Azure Policy.'
description: Azure Policy can help to apply at-scale enforcement and safeguards on
  your clusters in a centralized, consistent manner. It can also control what functions
  pods are granted and if anything is running against company policy.
source:
  type: wafsg
  file: ./checklists-ext/wafsg_checklist.en.json
resourceTypes:
- microsoft.containerservice/managedclusters
waf: Operations
severity: 1
labels:
  guid: 3dc59879-d877-4719-84d1-8262c08c7081
links: []
queries: {}
