name: wafsg-WorkloadArchitectureApplicationPerformance
title: 'Workload architecture: Monitor application performance with Azure Monitor.'
description: Configure Application Insights for code-based monitoring of applications
  running in an AKS cluster.
source:
  type: wafsg
  file: ./checklists-ext/wafsg_checklist.en.json
resourceTypes:
- microsoft.containerservice/managedclusters
waf: Operations
severity: 1
labels:
  guid: ea1485fc-32d7-46dc-a000-9e87c4834091
links: []
queries: {}
