name: wafsg-AutomatedDeploymentProcessesSoftwareDevelopmentLifecycle
title: 'Workload architecture: Use a repeatable and automated deployment processes
  for your workload within your software development lifecycle.'
description: ''
source:
  type: wafsg
  file: well-architected/service-guides/azure-kubernetes-service.md
  timestamp: July 24, 2024
resourceTypes:
- microsoft.containerservice/managedclusters
waf: Operations
severity: 1
labels:
  guid: a394bfb7-a185-4416-af7f-908ad78ba2cf
links: []
queries: {}
