name: wafsg-GlobalNetworkEnvironmentsCentralBasePolicy
title: Create Azure Firewall Policies to govern the security posture across global
  network environments. Assign policies to all instances of Azure Firewall.
description: Azure Firewall Policies can be arranged in an hierarchical structure
  to overlay a central base policy. Allow for granular policies to meet the requirements
  of specific regions. Delegate incremental firewall policies to local security teams
  through role-based access control (RBAC). Some settings are specific per instance,
  for example DNAT Rules and DNS configuration, then multiple specialized policies
  might be required.
source:
  type: wafsg
  file: ./checklists-ext/wafsg_checklist.en.json
resourceTypes:
- microsoft.network/azurefirewalls
waf: Reliability
severity: 1
labels:
  guid: 965fde84-1253-4833-93bc-9476a10ce2ad
links: []
queries: {}
