name: revcl-AppServiceEnvironmentIsolatedEnvironment-1-2-3
title: If deploying to an Isolated environment, use or migrate to App Service Environment
  (ASE) v3
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
resourceTypes:
- microsoft.web/sites
waf: Reliability
severity: 0
labels:
  guid: 82118ec5-ed6f-4c68-9471-eb0da98a1b34
links:
- type: docs
  url: https://learn.microsoft.com/azure/app-service/environment/intro
queries: {}
