guid: 03b125d5-b69b-4739-b7fd-84b86da4933e
name: NamedValues
title: Use Named Values to store common values that can be used in policies
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
services:
- APIM
resourceTypes:
- Microsoft.ApiManagement/service
waf: Operations
severity: 1
labels: {}
links:
- https://learn.microsoft.com/azure/api-management/api-management-howto-properties?tabs=azure-portal
queries: []
reviewed: August 26, 2024
