guid: ad119b63-dfca-446a-a65b-9f1e5849be6b
name: EndTransportLayerSecurity
title: Protect data in transit. Enable end-to-end Transport Layer Security (TLS),
  HTTP to HTTPS redirection, and managed TLS certificates when applicable. For more
  information, see TLS best practices for Azure Front Door.
description: ''
source:
  type: wafsg
  file: well-architected/service-guides/azure-front-door.md
  timestamp: July 24, 2024
services:
- Azure Front Door
resourceTypes:
- microsoft.network/frontdoors
waf: Security
labels: {}
links: []
queries: []
