name: revcl-AzureEventHubsNamespacesTransportLayerSecurity
title: 'Enforce a minimum required version of Transport Layer Security (TLS) for requests '
description: 'Azure Event Hubs namespaces permit clients to send and receive data
  with TLS 1.0 and above. To enforce stricter security measures, you can configure
  your Event Hubs namespace to require that clients send and receive data with a newer
  version of TLS. If an Event Hubs namespace requires a minimum version of TLS, then
  any requests made with an older version will fail. '
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
resourceTypes:
- microsoft.eventhub/namespaces
waf: Security
severity: 1
labels:
  guid: d2f54b29-769e-43a6-a0e7-828ac936657e
links:
- type: docs
  url: https://learn.microsoft.com/azure/event-hubs/transport-layer-security-configure-minimum-version
- type: docs
  url: https://learn.microsoft.com/learn/modules/secure-aad-users-with-mfa/
queries: {}
