name: wafsg-AppServicePlanLowerEnvironments
title: (App Service plan) Choose Free or Basic tiers for lower environments. We recommend
  these tiers for experimental use. Remove the tiers when you no longer need them.
description: The Free and Basic tiers are budget-friendly compared to higher tiers.
  They provide a cost-effective solution for nonproduction environments that don't
  need the full features and performance of premium plans.
source:
  type: wafsg
  file: ./checklists-ext/wafsg_checklist.en.json
resourceTypes:
- Microsoft.Web/sites
waf: Cost
labels:
  guid: dc84dbbc-6816-48ae-9926-e52e68d4273e
links: []
queries: {}
