guid: 1690d11b-f93e-4bc4-9db3-25e56a9b2699
name: ApplicationGatewayInstance
title: Review the impact of the interval and threshold settings on health probes
description: The health probe sends requests to the configured endpoint at a set interval.
  Also, there's a threshold of failed requests that will be tolerated before the backend
  is marked unhealthy. These numbers present a trade-off.- Setting a higher interval
  puts a higher load on your service. Each Application Gateway instance sends its
  own health probes, so 100 instances every 30 seconds means 100 requests per 30 seconds.-
  Setting a lower interval leaves more time before an outage is detected.- Setting
  a low unhealthy threshold might mean that short, transient failures might take down
  a backend. - Setting a high threshold it can take longer to take a backend out of
  rotation.
source:
  type: revcl
  file: ./checklists-ext/wafsg_checklist.en.json
services:
- Azure Application Gateway
resourceTypes:
- microsoft.network/applicationGateways
waf: Reliability
labels: {}
links: []
queries: []
reviewed: August 26, 2024
