guid: dc6efb36-f70f-41ed-aaf2-f8667781c123
name: Zone-AwareConfiguration
title: Deploy the instances in a zone-aware configuration, where available.
description: ''
source:
  type: wafsg
  file: well-architected/service-guides/azure-application-gateway.md
  timestamp: July 24, 2024
services:
- Azure Application Gateway
resourceTypes:
- microsoft.network/applicationGateways
waf: Reliability
labels: {}
links: []
queries: []
