name: wafsg-ApplicationGatewayInstanceCount
title: Estimate the Application Gateway instance count
description: ''
source:
  type: wafsg
  file: well-architected/service-guides/azure-application-gateway.md
  timestamp: July 24, 2024
resourceTypes:
- microsoft.network/applicationgateways
waf: Performance
severity: 1
labels:
  guid: 63dd2b1b-6076-46c9-8b80-54a255b77f49
links: []
queries: {}
