name: wafsg-AverageCurrentComputeUnitsApplicationGatewayVSku
title: Define the minimum instance count
description: For Application Gateway v2 SKU, autoscaling takes some time (approximately
  six to seven minutes) before the additional set of instances is ready to serve traffic.
  During that time, if there are short spikes in traffic, expect transient latency
  or loss of traffic.We recommend that you set your minimum instance count to an optimal
  level. After you estimate the average instance count and determine your Application
  Gateway autoscaling trends, define the minimum instance count based on your application
  patterns. For information, see Application Gateway high traffic support.Check the
  Current Compute Units for the past one month. This metric represents the gateway's
  CPU utilization. To define the minimum instance count, divide the peak usage by
  10. For example, if your average Current Compute Units in the past month is 50,
  set the minimum instance count to five.
source:
  type: wafsg
  file: ./checklists-ext/wafsg_checklist.en.json
resourceTypes:
- microsoft.network/applicationGateways
waf: Performance
labels:
  guid: af6f1096-14f3-465c-8691-b15cf5361942
links: []
queries: {}
