guid: a78b3d31-3170-44f2-b5d7-651a29f4ccf5
name: SapApplicationLayerComponents-541
title: Most failover clusters for SAP application layer components (ASCS) and the
  DBMS layer require a virtual IP address for a failover cluster.  Azure Load Balancer
  should handle the virtual IP address for all other cases. One design principle is
  to use one load balancer per cluster configuration. We recommend that you use the
  standard version of the load balancer (Standard Load Balancer SKU).
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
services:
- SAP
resourceTypes: []
waf: Reliability
severity: 0
labels: {}
links:
- https://learn.microsoft.com/azure/sap/workloads/high-availability-guide-standard-load-balancer-outbound-connections
- https://learn.microsoft.com/training/modules/implement-high-availability-for-sap-workloads-azure/?source=recommendations
queries: []
reviewed: August 26, 2024
