guid: 7c608f46-46b2-4cc0-bbd6-1d457c16671c
name: FunctionAppConfiguration
title: Ensure FUNCTIONS_WORKER_RUNTIME is set properly
description: |-
  The FUNCTIONS_WORKER_RUNTIME setting in the Function App configuration should be set to the appropriate value based on the language you are using. This setting is used to determine the language worker that will be used to execute your functions.
source:
  type: aprl
  file: azure-resources/Web/sites/recommendations.yaml
  timestamp: July 24, 2024
services:
- Microsoft.Web/sites
resourceTypes:
- Microsoft.Web/sites
severity: 1
labels:
  area: Governance
links: []
queries:
  arg: |-
    // cannot-be-validated-with-arg
