guid: b3808b9f-a1cf-4204-ad01-3a923ce474db
title: Use an ingress controller to expose web-based apps instead of exposing them
  with LoadBalancer-type services
source:
  type: revcl
  file: ./checklists/aks_checklist.en.json
services:
- AKS
resourceTypes: []
waf: Reliability
severity: 1
labels:
  area: Network Topology and Connectivity
  subarea: Scalability
  id: 06.06.01
links:
- https://learn.microsoft.com/azure/aks/concepts-network
queries: []
name: revcl-IngressController
