name: revcl-SapCloudApplicationCloudConnector
title: Enforce Principal propagation for forwarding the identity from SAP cloud application
  to SAP on-premises (Including IaaS) through cloud connector
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
resourceTypes: []
waf: Security
severity: 1
labels:
  guid: 45911475-e39e-4530-accc-d979366bcda2
links:
- type: docs
  url: https://learn.microsoft.com/azure/active-directory/fundamentals/scenario-azure-first-sap-identity-integration
- type: docs
  url: https://learn.microsoft.com/training/modules/explore-identity-services/2-explore-azure-virtual-machine-auth-access-control
queries: {}
