name: revcl-SapNetweaverBasedWebApplicationsSapWebGui-1
title: Implement SSO to SAP NetWeaver-based web applications like SAP Fiori and SAP
  Web GUI by using SAML.
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
resourceTypes: []
waf: Security
severity: 1
labels:
  guid: 9eb54dad-7861-4e1c-973a-f3bb003fc9c1
links:
- type: docs
  url: https://learn.microsoft.com/training/modules/explore-identity-services/6-exercise-integrate-azure-active-directory-sap-fiori
queries: {}
