guid: 785c2fa5-5b56-4ad4-a408-fe72734c476b
name: BlueGreenDeployments
title: Use canary or blue/green deployments
source:
  type: revcl
  file: ./checklists/aks_checklist.en.json
resourceTypes: []
waf: Operations
severity: 1
labels:
  area: Application Deployment
  subarea: Development
  id: 01.01.01
links:
- https://learn.microsoft.com/azure/architecture/reference-architectures/containers/aks/secure-baseline-aks
queries: []
reviewed: August 26, 2024
