guid: 6e31b67d-67ba-4591-89c0-9e805d597c7e
name: BusinessCriticalApplications
title: For Business Critical Applications, use Active Active configuration
description: Should be used for DR configurations where an outage or loss of event
  data in the downed region cannot be tolerated. For these cases, follow the replication
  guidance and do not use the built-in geo-disaster recovery capability (active/passive).
  With Active/Active, Maintain multiple Event Hubs in different regions and namespaces,
  and events will be replicated between the hubs
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
services:
- Event Hubs
resourceTypes:
- microsoft.eventhub/namespaces
waf: Reliability
severity: 1
labels: {}
links:
- https://learn.microsoft.com/azure/event-hubs/event-hubs-federation-overview
queries: []
reviewed: August 26, 2024
