name: revcl-SelfHostedGatewayDeployments
title: Ensure that the self-hosted gateway deployments are resilient.
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
resourceTypes:
- Microsoft.ApiManagement/service
waf: Reliability
severity: 0
labels:
  guid: 10f58602-f0f9-4d77-972a-956f6e0f2600
links:
- type: docs
  url: https://learn.microsoft.com/en-us/azure/api-management/self-hosted-gateway-overview
queries: {}
