guid: 189ea962-3969-4863-8f5a-5ad808c2cf4b
name: AzureFrontDoorWafConfiguration
title: Define your Azure Front Door WAF configuration as code. By using code, you
  can more easily adopt new rule set version and gain additional protection.
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
services:
- Front Door
resourceTypes:
- microsoft.network/frontdoors
waf: Operations
severity: 1
labels: {}
links:
- https://learn.microsoft.com/azure/web-application-firewall/afds/waf-front-door-best-practices#define-your-waf-configuration-as-code
queries: []
reviewed: August 26, 2024
