name: revcl-AzureFrontDoorWafLogsDiagnosticSettings
title: Add diagnostic settings to save your Azure Front Door WAF logs.
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
resourceTypes:
- microsoft.network/frontdoors
waf: Operations
severity: 1
labels:
  guid: 4cea4050-7946-4a7c-89e6-b021b73c352d
links:
- type: docs
  url: https://learn.microsoft.com/azure/web-application-firewall/afds/waf-front-door-best-practices#add-diagnostic-settings-to-save-your-wafs-logs
queries: {}
