name: wafsg-AzureFrontDoorConfigurationCriticalOperationalIssues
title: Capture logs and metrics.  Include resource activity logs, access logs, health
  probe logs, and WAF logs. Set up alerts.
description: Monitoring ingress flow is a crucial part of monitoring an application.
  You want to track requests and make performance and security improvements. You need
  data to debug your Azure Front Door configuration.  With alerts in place, you can
  get instant notifications of any critical operational issues.
source:
  type: wafsg
  file: ./checklists-ext/wafsg_checklist.en.json
resourceTypes:
- microsoft.network/frontdoors
waf: Operations
labels:
  guid: 90aa5326-da06-4070-bcb0-26d31648029a
links: []
queries: {}
