name: wafsg-WildcardTlsCertificatesConfiguration
title: Use wildcard TLS certificates.
description: You don't need to modify the configuration to add or specify each subdomain
  separately.
source:
  type: wafsg
  file: ./checklists-ext/wafsg_checklist.en.json
resourceTypes:
- microsoft.network/frontdoors
waf: Operations
severity: 1
labels:
  guid: bf934891-a9a1-49f7-9036-ea7ba9630bdc
links: []
queries: {}
