guid: dac421ec-2832-4c37-839e-b6dc5a38f2fa
name: ExistingApplicationMonitoringScenarios
title: Convert Classic Deployments
description: |-
  Classic Application Insights retires in February 2024. To minimize disruption to existing application monitoring scenarios, transition to workspace-based Application Insights before 29 February 2024.
source:
  type: aprl
  file: azure-resources/Insights/components/recommendations.yaml
  timestamp: July 24, 2024
services:
- Microsoft.Insights/components
resourceTypes:
- Microsoft.Insights/components
severity: 1
labels:
  area: Service Upgrade and Retirement
links: []
queries:
  arg: "// Azure Resource Graph query\n// Filters Application Insights resources with\
    \ \u2018Classic\u2019 deployment type\nresources\n| where type =~ \"microsoft.insights/components\"\
    \n| extend IngestionMode = properties.IngestionMode\n| where IngestionMode =~\
    \ 'ApplicationInsights'\n| project recommendationId= \"dac421ec-2832-4c37-839e-b6dc5a38f2fa\"\
    , name, id, tags, param1=\"ApplicationInsightsDeploymentType: Classic\"\n"
