name: wafsg-AzureMonitorAutoscaleFeatureAksDeploymentEnvironments
title: "Model deployment environment scaling: Use the deployment environment\u2019\
  s autoscale capabilities. For AKS deployment environments, use the cluster autoscaler\
  \ to scale to meet demand. For online endpoints, automatically scale via integration\
  \ with the Azure Monitor autoscale feature."
description: Autoscaling adjusts the number of instances of the deployed model to
  match demand.
source:
  type: wafsg
  file: ./checklists-ext/wafsg_checklist.en.json
resourceTypes:
- microsoft.machinelearningservices/workspaces
waf: Performance
severity: 1
labels:
  guid: bc3729bc-45fd-4ceb-9b5d-2135464eddfb
links: []
queries: {}
