name: wafsg-DeploymentEnvironmentsAutoscalingCapabilities
title: 'Meet capacity requirements: Choose deployment environments with autoscaling
  capabilities to add and remove capacity as demand fluctuates.'
description: ''
source:
  type: wafsg
  file: well-architected/service-guides/azure-machine-learning.md
  timestamp: July 24, 2024
resourceTypes:
- microsoft.machinelearningservices/workspaces
waf: Performance
severity: 1
labels:
  guid: def7165b-3e46-4bab-b1a1-a24681c4cacc
links: []
queries: {}
