name: revcl-MinimumTlsPolicyAppServiceConfiguration
title: Set minimum TLS policy to 1.2
description: Set minimum TLS policy to 1.2 in App Service configuration.
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
resourceTypes:
- microsoft.web/sites
waf: Security
severity: 1
labels:
  guid: c115775c-2ea5-45b4-9ad4-8408ee72734b
links:
- type: docs
  url: https://learn.microsoft.com/azure/app-service/configure-ssl-bindings#enforce-tls-versions
queries:
  arg: appserviceresources | where type =~ 'microsoft.web/sites/config' | extend compliant
    = (properties.MinTlsVersion>=1.2) | distinct id,compliant
