guid: 35c2f653-acd6-471c-91a9-f7e4a3fcce3e
name: Dns)ProxyConfiguration
title: Enable Azure Firewall (DNS) proxy configuration.
description: Enabling this feature points clients in the VNets to Azure Firewall as
  a DNS server. It will protect internal DNS infrastructure that will not be directly
  accessed and exposed. Azure Firewall must be also configured to use custom DNS that
  will be used to forward DNS queries.
source:
  type: revcl
  file: ./checklists-ext/wafsg_checklist.en.json
services:
- Azure Firewall
resourceTypes:
- Microsoft.Network/azureFirewalls
waf: Security
labels: {}
links: []
queries: []
reviewed: August 26, 2024
