name: aprl-AzureContainerRegistriesDiagnosticSettings
title: Configure Diagnostic Settings for all Azure Container Registries
description: |-
  Resource Logs are not collected and stored until you create a diagnostic setting and route them to one or more locations.
source:
  type: aprl
  file: azure-resources/ContainerRegistry/registries/recommendations.yaml
  timestamp: July 24, 2024
resourceTypes:
- Microsoft.ContainerRegistry/registries
severity: 1
labels:
  guid: 44107155-7a32-9348-89f3-d5aa7e7c5a1d
  area: Monitoring and Alerting
links: []
queries:
  arg: |
    // cannot-be-validated-with-arg
