name: revcl-SecondaryDisasterRecoveryEnvironmentGeopoliticalRegionPair
title: Use the geopolitical region pair as the secondary disaster recovery environment
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
resourceTypes:
- microsoft.avs/privateclouds
waf: Reliability
severity: 1
labels:
  guid: 8255461e-2aee-4345-9aec-8339248b262d
links: []
queries: {}
