guid: 1c10e986-48da-4cf8-acd6-2a7f7c940735
name: ApplicationGatewayCapacityChanges
title: Be aware of Application Gateway capacity changes when enabling WAF
description: ''
source:
  type: wafsg
  file: well-architected/service-guides/azure-application-gateway.md
  timestamp: July 24, 2024
services:
- Azure Application Gateway
resourceTypes:
- microsoft.network/applicationGateways
waf: Security
labels: {}
links: []
queries: []
