guid: fb24f724-e47b-46ec-a3cb-426fe159fdbf
name: ApplicationGatewayCapacityChanges
title: Be aware of Application Gateway capacity changes when enabling WAF
description: When WAF is enabled, every request must be buffered by the Application
  Gateway until it fully arrives, checks if the request matches with any rule violation
  in its core rule set, and then forwards the packet to the backend instances. When
  there are large file uploads (30MB+ in size), it can result in a significant latency.
  Because Application Gateway capacity requirements are different with WAF, we do
  not recommend enabling WAF on Application Gateway without proper testing and validation.
source:
  type: revcl
  file: ./checklists-ext/wafsg_checklist.en.json
services:
- Azure Application Gateway
resourceTypes:
- microsoft.network/applicationGateways
waf: Security
labels: {}
links: []
queries: []
