name: revcl-BlueGreenDeploymentStrategiesAzureSpringApps
title: Azure Spring Apps permits two deployments for every app, only one of which
  receives production traffic. You can achieve zero downtime with blue green deployment
  strategies. Blue green deployment is only available in Standard and Enterprise tiers.
  You could automate deployment using CI/CD with ADO/GitHub actions
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
resourceTypes:
- microsoft.appplatform/spring
waf: Reliability
severity: 1
labels:
  guid: 6d8e32a8-3892-479d-a40b-10f6b4f6f298
links:
- type: docs
  url: https://learn.microsoft.com/azure/spring-apps/concepts-blue-green-deployment-strategies
queries: {}
