guid: 6cf7bc2c-7416-48d1-8966-05f18b4c77dc
name: Third-PartySecurity
title: Determine if you want to use third-party security as a service (SECaaS) providers.
description: ''
source:
  type: wafsg
  file: well-architected/service-guides/azure-firewall.md
  timestamp: July 24, 2024
services:
- Azure Firewall
resourceTypes:
- Microsoft.Network/azureFirewalls
waf: Security
labels: {}
links: []
queries: []
