name: wafsg-CurateModelTrainingEnvironmentsUnnecessaryImageBuilds
title: 'Curate model training environments: Use curated environments optimized for
  Machine Learning, when available.'
description: Curated environments are pre-created environments provided by Machine
  Learning that speed up deployment time and reduce deployment and training latency.
  Using curated environments improves training and deployment success rates and avoids
  unnecessary image builds. Curated environments, such as Azure Container for PyTorch,
  can also be optimized for training large models on Machine Learning.
source:
  type: wafsg
  file: ./checklists-ext/wafsg_checklist.en.json
resourceTypes:
- microsoft.machinelearningservices/workspaces
waf: Operations
severity: 1
labels:
  guid: 4addefe4-a8b2-4b05-8483-c8a96ada0ee0
links: []
queries: {}
