name: wafsg-CuratedEnvironmentsMachineLearning
title: 'Simplicity: Use curated environments optimized for Machine Learning, when
  available.'
description: ''
source:
  type: wafsg
  file: well-architected/service-guides/azure-machine-learning.md
  timestamp: July 24, 2024
resourceTypes:
- microsoft.machinelearningservices/workspaces
waf: Operations
severity: 1
labels:
  guid: d0afa393-bcfd-4e72-8cd2-304a988a6d0a
links: []
queries: {}
