name: aprl-ZoneRedundantContainerAppEnvironmentsContainerAppsEnvironment
title: Deploy zone redundant Container app environments
description: |-
  To take advantage of availability zones, you must enable zone redundancy when you create a Container Apps environment. The environment must include a virtual network with an available subnet. To ensure proper distribution of replicas, set your app's minimum replica count to three.
source:
  type: aprl
  file: azure-resources/App/managedEnvironments/recommendations.yaml
  timestamp: July 24, 2024
resourceTypes:
- Microsoft.App/managedenvironments
severity: 0
labels:
  guid: f4201965-a88d-449d-b3b4-021394719eb2
  area: High Availability
links: []
queries:
  arg: |-
    // Azure Resource Graph Query
    // The query filters the qualified Container app environments that do not have Zone Redundancy enabled.
    resources
    | where type =~ "microsoft.app/managedenvironments"
    | where tobool(properties.zoneRedundant) == false
    | project recommendationId = "f4201965-a88d-449d-b3b4-021394719eb2", name, id, tags, param1 = "AvailabilityZones: Single Zone"
    | order by id asc
