name: revcl-SapDatabaseServerSapApplication
title: "It is not supported to deploy any NVA between SAP application and SAP Database\xC2\
  \_server"
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
resourceTypes: []
waf: Performance
severity: 0
labels:
  guid: 41742694-3ff8-4ae7-b7d4-743176c8bcbf
links:
- type: docs
  url: https://learn.microsoft.com/azure/sap/workloads/planning-guide
- type: docs
  url: https://me.sap.com/notes/2731110
queries: {}
