name: wafsg-MachineLearningComputeEnvironmentsRequiringCodeSigning
title: 'Integrity: Require code used for training in Machine Learning compute environments
  to be signed. Requiring code signing ensures that the code running is from a trusted
  source and hasn''t been tampered with.'
description: ''
source:
  type: wafsg
  file: well-architected/service-guides/azure-machine-learning.md
  timestamp: July 24, 2024
resourceTypes:
- Microsoft.MachineLearningServices/workspaces
waf: Security
labels:
  guid: 69440a0f-3fab-4ea2-95b1-ba0ec1c637fc
links: []
queries: {}
