guid: 3bbf1b68-e6d6-475b-9406-9271cdee6454
name: AzureOpenaiApplications
title: 'Achieve performance: For applications like chatbots or conversational interfaces,
  consider implementing streaming. Streaming can enhance the perceived performance
  of Azure OpenAI applications by delivering responses to users in an incremental
  manner, improving the user experience.'
description: ''
source:
  type: wafsg
  file: well-architected/service-guides/azure-openai.md
  timestamp: July 24, 2024
services:
- Azure Openai
resourceTypes:
- Microsoft.CognitiveServices/accounts
waf: Performance
labels: {}
links: []
queries: []
