name: Get APRL checklists
on:
    # schedule:
    #     - cron: '0 0 * * 0'  # every Sunday at midnight
    workflow_dispatch:
jobs:
  get-aprl:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Get the APRL checklist
    - name: Retrieve the APRL checklists
      uses: ./.github/actions/get_aprl
      with:
        output_file: './checklists-ext/aprl_checklist.en.json'
        verbose: 'true'
    # Create a PR
    - name: Create pull request
      uses: peter-evans/create-pull-request@v3.10.1
      with:
        title: 'Latest version of the APRL checklists retrieved'
        body: 'This PR is to retrieve the latest version of the APRL checklists.'
        token: ${{ secrets.WORKFLOW_PAT }}
