guid: 02610076-047b-4f48-9c50-0172c4bac957
name: MatchTimeoutSettings
title: Match timeout settings with the backend application
description: ''
source:
  type: wafsg
  file: well-architected/service-guides/azure-application-gateway.md
  timestamp: July 24, 2024
services:
- Azure Application Gateway
resourceTypes:
- microsoft.network/applicationGateways
waf: Operations
labels: {}
links: []
queries: []
