guid: ee3b1f28-7d23-484a-a721-a0e0da65aed8
name: WebApplicationFirewall-136
title: Enable diagnostics on Application Gateway and Web Application Firewall (WAF)
description: Diagnostic logs allow you to view firewall logs, performance logs, and
  access logs. Use these logs to manage and troubleshoot issues with Application Gateway
  instances. For more information, see Back-end health and diagnostic logs for Application
  Gateway.
source:
  type: revcl
  file: ./checklists-ext/wafsg_checklist.en.json
services:
- Azure Application Gateway
resourceTypes:
- microsoft.network/applicationGateways
waf: Operations
labels: {}
links: []
queries: []
