guid: dce9793b-7bcd-4b3b-91eb-2ec14eea6e59
name: SiteDisasterToleranceSettings
title: Have site disaster tolerance settings been properly considered and changed
  for your business if needed.
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
services:
- AVS
resourceTypes:
- Microsoft.AVS/privateClouds
waf: Reliability
severity: 0
labels: {}
links:
- https://learn.microsoft.com/azure/frontdoor/best-practices#use-managed-tls-certificates
queries: []
reviewed: August 26, 2024
